stages:
  - build
  - test
  - release

include:
  - 'https://ci-files.skypicker.com/analysis/precommit.v3.yml'
  - 'https://ci-files.skypicker.com/templates/build/tox_init.yml'
  - 'https://ci-files.skypicker.com/templates/test/tox_tests.yml'
  - 'https://ci-files.skypicker.com/templates/release/pypi_upload.yml'
  - 'https://ci-files.skypicker.com/release/twine.src.v1.yml'

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH
    - if: $CI_COMMIT_TAG
    - if: $CI_MERGE_REQUEST_ID

variables:
  PYPI_CONFIG: |
    [distutils]
    index-servers = kiwi

    [kiwi]
    repository: https://pypi.skypicker.com/pypi/
    username: $PYPI_USERNAME
    password: $PYPI_PASSWORD

pypi_upload:
  when: manual

release-public:
  extends: .twine-upload
  variables:
    TWINE_REGISTRY: https://upload.pypi.org/legacy/
    REGISTRY_USERNAME: $PYPIORG_USERNAME
    REGISTRY_PASSWORD: $PYPIORG_PASSWORD
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: manual


release_unstable:
  stage: release
  image: python:3.10-alpine
  variables:
    VERSION_FILE: VERSION
  script:
   - echo "`cat $VERSION_FILE`.dev$(date +'%s')" > $VERSION_FILE
   - echo "$PYPI_CONFIG" > ~/.pypirc
   - pip install wheel
   - python setup.py bdist_wheel --universal upload -r kiwi
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: manual


pages:
  stage: release
  image: python:3.10-alpine
  script:
   - apk add --no-cache make
   - pip install -r requirements.txt -r test-requirements.txt -r docs-requirements.txt -e .
   - sphinx-apidoc --output-dir docs/kw --no-toc kw && make --directory=docs html
   - mv docs/_build/html public
  artifacts:
    paths:
     - public
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
