stages:
  - build
  - test
  - release

include:
  - 'https://ci-files.skypicker.com/templates/build/pre_commit.yml'
  - 'https://ci-files.skypicker.com/templates/build/tox_init.yml'
  - 'https://ci-files.skypicker.com/templates/test/tox_tests.yml'
  - 'https://ci-files.skypicker.com/templates/release/pypi_upload.yml'

pypi_upload:
  only:
    changes:
      - setup.py

pages:
  stage: release
  image: python:3.10-alpine
  script:
   - apk add --no-cache make
   - pip install -r requirements.txt -r test-requirements.txt -r docs-requirements.txt -e .
   - sphinx-apidoc --output-dir docs/kw --no-toc kw && make --directory=docs html
   - mv docs/_build/html public
  artifacts:
    paths:
     - public
  only:
   - master
