[tox]
skipsdist = true
envlist = {integration,unit}_tests-py{310,311,312,313}

[testenv]
deps =
  -rrequirements.txt
  -rtest-requirements.txt
basepython =
  py310: python3.10
  py311: python3.11
  py312: python3.12
  py313: python3.13
commands =
  unit_tests: pytest {posargs:} --cov kw/structlog_config test/unit
